apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: port-scanner
spec:
  schedule: "* 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: port-scanner
            image: deveshs23/port-scanner:v0.1
            imagePullPolicy: Always
            volumeMounts:
              - name: configmap
                mountPath: /app/port-scanner/config.yaml
                subPath: config.yaml
          restartPolicy: OnFailure
          volumes:
            - name: configmap
              configMap:
                name: scanner-config
                defaultMode: 420
